### ISSUE TITLE
Cake 2: small fix in ShimModel

### ISSUE THREAD

**Issue by fstark-fms** [dereuromark/cakephp-shim#102]
Small update needed to prevent an error when a time is submitted which includes 'meridian'.

class ShimModel, line 490 contains an illegal string offset 'meridian'

please change 
- $data == 'pm'['meridian']
into 
- $data['meridian'] == 'pm'

and on line 494, please change
- if (isset($data['hour']) && isset($data['meridian']) && $data['hour'] == 12 && $data == 'am'['meridian']) {
into 
-  if (isset($data['hour']) && isset($data['meridian']) && $data['hour'] == 12 && $data['meridian'] == 'am') {

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-shim/commit/05f9af1e9e9ca445bce159d1ea53367442e02c0a
