### ISSUE TITLE
The association bindings in 2.x branch are not permanent

### ISSUE THREAD

**Issue by Noahbrat** [dereuromark/cakephp-shim#13]
The _setAssoc method that is called by the belongsTo/haMany/etc methods is calling the bindModel method with the reset option set to true in the 2.x branch. This will create temporary relationships, and I think it's intended to create permanent associations.

**Comment by dereuromark** [comment]
I see.
do you have an idea for a fix in mind?

**Comment by Noahbrat** [comment]
Yes, the bindModel's second param should be changed to false in the _setAssoc method. Looks like line 777.

**Comment by dereuromark** [comment]
Are you able to provide a fix as PR? otherwise I can look into it these days.

**Comment by Noahbrat** [comment]
I was attempting to do that, but I haven't been able to figure it out. Do I have to have permissions to push a new branch and do a pull request? Sorry, obviously haven't done much contributing.

**Comment by dereuromark** [comment]
You can fork to your account, and then you can do that :)

**Comment by Noahbrat** [comment]
Awww... thank you.
