### ISSUE TITLE
The signature of initialize is not the same as in Cake 3.x

### ISSUE THREAD

**Issue by bancer** [dereuromark/cakephp-shim#16]
In ShimModel: 
`public function initialize($id = false, $table = null, $ds = null)`.
In Table: 
`public function initialize(array $config)`

**Comment by dereuromark** [comment]
Are you confusing 2.x and 3.x?
https://github.com/dereuromark/cakephp-shim/blob/2.x/Model/ShimModel.php#L25-L26 is exactly how 2.x is supposed to be AFAIK.

**Comment by bancer** [comment]
What's the point of making `initialize` function to have the same parameters as the constructor? It will not help to migrate the models because the signature of this method in every model will need to be changed. And it will not be possible to use these parameters when the code is migrated to Cake 3.x.

**Comment by bancer** [comment]
What do you think about [this](https://github.com/cakephp/cakephp/pull/11703/files#diff-bcc20f407d44532dc3db66d6b0ed9f55R782) approach?

**Comment by dereuromark** [comment]
This is out of scope.
Signature changes trigger php warnings.

**Comment by dereuromark** [comment]
Its simple: dont overwrite constructors. use initialize() etc

**Comment by bancer** [comment]
I do not understand. There is no `initialize` method in Model class. How can it trigger PHP warnings?

**Comment by dereuromark** [comment]
Ah you are right. Do you think we can fix this in a minor release?

**Comment by bancer** [comment]
I believe so.

**Comment by dereuromark** [comment]
Please make a pr

**Comment by dereuromark** [comment]
Actually, thinking about it more. Then we should separate those.
As `$config` array of 3.x is sth different than `$id = false, $table = null, $ds = null` of 2.x

**Comment by dereuromark** [comment]
PR https://github.com/dereuromark/cakephp-shim/pull/17 open.
