### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by bancer** [dereuromark/cakephp-shim#22]
> Use Configure::write('Shim.checkPaths', true); to assert that all paths are correctly set up, including a trailing DS and the correct directory separator (as DS constant).
https://github.com/dereuromark/cakephp-shim/blob/2.x/docs/Features.md#debugging

It is not clear how is that related to the migration to Cake 3.x. Are the trailing slashes mentioned anywhere in the migration guides? Does Cake 3.x handle the trailing slashes differently than Cake 2.x?

**Comment by dereuromark** [comment]
This is cakephp default, so not specific to 3.x, but it will make upgrading easier as well.

**Comment by dereuromark** [comment]
Just see it as an additional useful check.
