### ISSUE TITLE
Shim.modelExists is unusable

### ISSUE THREAD

**Issue by bancer** [dereuromark/cakephp-shim#25]
It is practically impossible to use 'Shim.modelExists' because too many errors are generated from Cake core in multiple plases, f.ex. in [Cake/Model/Model.php:1827](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Model.php#L1827).

**Comment by bancer** [comment]
Maybe id parameter should be added to all `exists()` calls in the core?

**Comment by bancer** [comment]
The fix - https://github.com/cakephp/cakephp/pull/12692.

**Comment by dereuromark** [comment]
Closing as core PR is open.
