### ISSUE TITLE
Shim.deprecateField fails in TreeBehavior

### ISSUE THREAD

**Issue by aritonandrei** [dereuromark/cakephp-shim#28]
I've tried to use `Shim.deprecateField`  but i got an error from cake core.
[Cake/Model/Behavior/TreeBehavior.php:L253](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Behavior/TreeBehavior.php#L253)

**Comment by dereuromark** [comment]
What is your exact error?

**Comment by aritonandrei** [comment]
`Using implicit Model->id is deprecated in shim context. Pass it as conditions part instead.`
A possible solution i think is to replace  `field` method with `fieldByConditions`

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-shim/blob/2.x/Model/Behavior/TreeShimBehavior.php

**Comment by dereuromark** [comment]
I improved the docs a bit: https://github.com/dereuromark/cakephp-shim/commit/aed81d57f5cac2ab9103537fc6c1f308c4d8d6d5

**Comment by aritonandrei** [comment]
Thank you.
