### ISSUE TITLE
EventManager => CakeEventManager

### ISSUE THREAD

**Issue by gemal** [dereuromark/cakephp-shim#31]
in:
https://github.com/dereuromark/cakephp-shim/blob/2.x/TestSuite/ShimIntegrationTestCase.php

you have:
`App::uses('EventManager', 'Event');`

shouldn't this be:
`App::uses('CakeEventManager', 'Event');`

**Comment by dereuromark** [comment]
Sure? if so, please PR

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-shim/pull/32
