### ISSUE TITLE
Error: Class 'Shim' not found

### ISSUE THREAD

**Issue by gemal** [dereuromark/cakephp-shim#68]
in
`FormShimHelper.php`

you have:
`Shim::check(Shim::FORM_INPUTS, $message);`

but the import is missing

**Comment by dereuromark** [comment]
what import? what versio/branch? Without details this is had to confirm

**Comment by gemal** [comment]
yes sorry.
we use
`"dereuromark/cakephp-shim": "cake2-dev",`

adding
`App::uses('Shim', 'Shim.Lib');`

fixes it

**Comment by dereuromark** [comment]
Can you make a PR please?
I dont use 2.x anymore for some time now.
