### ISSUE TITLE
Table::save checks for "is_array(options)" on ArrayObject

### ISSUE THREAD

**Issue by chtheis** [dereuromark/cakephp-shim#84]
I use cakephp_shim to use some 2.x code in CakePHP 4.x
In shim Table::save, line 393 calls
  if (!is_array(options)) 
and throws an exception if that is not true.

In CakePHP Table::_saveMany (which in turns calls shim Table::save) line 2183 an ArrayObject is constructed out of the options argument. In due turn above mentioned check is_array(options) must fail.

**Comment by dereuromark** [comment]
Could this already be fixed on master?
https://github.com/dereuromark/cakephp-shim/compare/2.0.1...master#diff-d2fd5967251c9a1be8184026ca95a235R398

If so, I can tag a new release now.

**Comment by chtheis** [comment]
I did not check but the code looks like it handles my situation instead of throwing an exception.  So yes, I appreciate if you tag a new release :)

What I'm wondering is that you just cast to array without any further check. Is this intended?

**Comment by dereuromark** [comment]
Yes, due to `array|\ArrayAccess`

**Comment by chtheis** [comment]
OK

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-shim/releases/tag/2.1.0

**Comment by chtheis** [comment]
YES, it is working :) Thanks a lot!
